In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#%matplotlib inline
#%matplotlib notebook
plt.rcParams["figure.figsize"] = (10,6)
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [6]:
df = pd.read_csv('iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0           5.100        3.500         1.400        0.200     setosa
1           4.900        3.000         1.400        0.200     setosa
2           4.700        3.200         1.300        0.200     setosa
3           4.600        3.100         1.500        0.200     setosa
4           5.000        3.600         1.400        0.200     setosa
..            ...          ...           ...          ...        ...
145         6.700        3.000         5.200        2.300  virginica
146         6.300        2.500         5.000        1.900  virginica
147         6.500        3.000         5.200        2.000  virginica
148         6.200        3.400         5.400        2.300  virginica
149         5.900        3.000         5.100        1.800  virginica

[150 rows x 5 columns]